### ISSUE TITLE
NoMethodError on partials when upgrading to rabl 0.11.2 and above

### ISSUE THREAD

**Issue by ronenm** [ruby-grape/grape-rabl#31]
Hi,

I'm using the following (and other) partial in my rabl views for grape:

```
  node :images do |partner|
      partial("images", :object => partner.gallery.attachments)
 end
```

When upgrading to the latest rabl (0.11.4) I noticed that I'm starting to get the following error message:

NoMethodError (undefined method `views' for #<Grape::Util::HashStack:0x007ffb4d9d08a0>):
  app/views/api/partner.rabl:7:in`block in eval_source'

Going backward I saw that this error message started to appear at rabl 0.11.2 (it works fine in 0.11.1).

Thanks,
Ronen

**Comment by ronenm** [comment]
קהילת הטרמפים Ronen Moldovan מזמין אותך להתחיל לשתף נסיעות! משתפים נסיעות עם נהגים וטרמפיסטים שנוסעים במסלול שלכם. מתחלקים בהוצאות הנסיעה וחוסכים כסף. Ronen שלח לך 20 מטבעות עבור נסיעות בחינם. קבל/י את ההזמנה של Ronen אל תפספסו הזדמנויות לטרמפ! הורידו את האפליקציה: המייל הזה נשלח אליך מRonen Moldovan. אם אינך רוצה להמשיך לקבל מיילים כאלה לחצ/י הסר יש לך שאלות? אנחנו כאן כדי לעזור! צור קשר

**Comment by ronenm** [comment]
קהילת הטרמפים Ronen Moldovan מזמין אותך להתחיל לשתף נסיעות! משתפים נסיעות עם נהגים וטרמפיסטים שנוסעים במסלול שלכם. מתחלקים בהוצאות הנסיעה וחוסכים כסף. Ronen שלח לך 20 מטבעות עבור נסיעות בחינם. קבל/י את ההזמנה של Ronen אל תפספסו הזדמנויות לטרמפ! הורידו את האפליקציה: המייל הזה נשלח אליך מRonen Moldovan. אם אינך רוצה להמשיך לקבל מיילים כאלה לחצ/י הסר יש לך שאלות? אנחנו כאן כדי לעזור! צור קשר
